import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = int(os.getenv("TELEGRAM_CHAT_ID"))

SYMBOLS = [
    # Top 20 crypto pairs (example)
    "BTCUSDT", "ETHUSDT", "XRPUSDT", "SOLUSDT", "ADAUSDT", "DOGEUSDT", "DOTUSDT", "MATICUSDT", "LTCUSDT", "LINKUSDT",
    "BCHUSDT", "XLMUSDT", "ATOMUSDT", "ETCUSDT", "FILUSDT", "TRXUSDT", "EOSUSDT", "VETUSDT", "NEOUSDT", "ALGOUSDT",
    # Top 10 forex pairs + XAUUSD & USDJPY
    "XAUUSD", "USDJPY", "EURUSD", "GBPUSD", "AUDUSD", "USDCAD", "USDCHF", "NZDUSD", "EURJPY", "GBPJPY", "AUDJPY"
]

INTERVAL = "1h"
CHECK_INTERVAL_SECONDS = 300  # 5 minutes
